services:
  web:
    build:
      context: front
    ports:
      - 4200:4200
    volumes:
      - ./front:/project
      - /project/node_modules

  api:
    build:
      context: server
    ports:
      - 8000:8000
    volumes:
      - ./server:/app

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nbp_service
      - POSTGRES_USER=postgres


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
