services:
  web:
    build:
      context: front
    ports:
      - 4200:4200
    volumes:
      - ./front:/project
      - /project/node_modules

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=nbp_viewer
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080